apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelines-dashboard
spec:
  template:
    spec:
      containers:
        - name: pipelines-dashboard
          image: registry.zazuko.com/docker/pipelines-dashboard
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          env:
            - name: GITLAB
              value: https://gitlab.ldbar.ch
            - name: OIDC_CLIENT_ID
              value: c6b7e6f2aba6f17ca6b314148a762d88e15ace28f99f3b8f415feff0e0b7ed25
            - name: PUBLIC_URL
              value: https://pipelines-dashboard.zazuko.net

          livenessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /
              port: http

          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /
              port: http
