apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelines-dashboard
spec:
  template:
    spec:
      containers:
        - name: pipelines-dashboard
          image: ghcr.io/zazuko/pipelines-dashboard
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          envFrom:
            - configMapRef:
                name: dashboard-config

          livenessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /
              port: http

          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /
              port: http
