apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pipelines-dashboard

commonLabels:
  app.kubernetes.io/name: pipelines-dashboard

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
